name: pocket_pal
description: Expense Tracking Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  shared_preferences: ^2.0.18
  provider: ^6.0.5

  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.4.1
  
  image_picker: ^0.8.7
  flutter_screenutil: ^5.7.0
  flutter_slidable: ^2.0.0
  pie_chart: ^5.3.2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  connectivity_plus: ^3.0.5
  table_calendar: ^3.0.8
  shortid: ^0.1.2
  
  glassmorphism: ^3.0.0
  flutter_zoom_drawer: ^3.0.4+1
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.3
  flutter_feather_icons: ^2.0.0+1
  hidden_drawer_menu: ^3.0.1
  flutter_native_splash: ^2.2.19
  
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboard_image1.jpg
    - assets/images/onboard_image2.jpg
    - assets/images/onboard_image3.jpg
    - assets/images/onboard_image4.jpg

    - assets/svg/NoWifi.svg
    - assets/svg/forgot_password.svg
    - assets/svg/Error.svg
    - assets/svg/dashboard_card.svg
    - assets/svg/welcome_doggie.svg

    - assets/icon/Facebook.svg
    - assets/icon/Github.svg
    - assets/icon/Google.svg
    - assets/icon/Menu.svg
    
    - assets/icon/Folder.svg
    - assets/icon/Folder_lg.svg

    - assets/icon/Envelope.svg
    - assets/icon/Envelope_lg.svg

    - assets/icon/peso_sign.svg

    - assets/images/Splash.png
    - assets/images/envelope_bg.png
    - assets/images/bg.png

flutter_native_splash:
  color : "#FFFFFF"
  image : assets/images/Splash.png


flutter_launcher_icons:
  android : true 
  image_path : "assets/images/Profile2.png"
  adaptive_icon_background : "assets/images/Splash.png"